### ISSUE TITLE
Preferences window appears in strange place

### ISSUE THREAD

**Issue by gingerbeardman** [roeybiran/finbar-issues#10]
On the first run of Finbar I wanted to set a hotkey so I summoned preferences. 

> I can't remember if I used Cmd+Comma or the menu bar item

I've never seen a preferences window appear like this: it was "on" the lower left corner, partially off screen. 

> I can't get it to reproduce, I'll try reinstalling later

I'd expect a preferences window to be centred on the current display (ie the display that Finbar was summoned on if there's more than one display)

My setup
- macOS 12.6.8
- Finbar latest as of MJ Tsai blog post
- two displays
- external as main display
- external display is portrait orientation

**Comment by roeybiran** [comment]
Hi, the next update will see this issue fixed, partially — the settings window will be centered, and so does the rule editor’s window. However, the display on which this will happen will still be left at the system’s discernment — which I’m almost certain would always be what the system considers the “main”, or active, display.

Making each of these windows appear on the desired screen, dynamically, requires a lot of extra logic, which I thought to be necessary only for the app’s main window.

Please tell me whether do you find this to be an acceptable solution.

Roey

**Comment by gingerbeardman** [comment]
I think what you're describing is optimal, so sounds good to me!

**Comment by roeybiran** [comment]
Fantastic! Ping me again if you change your mind.

Fixed in v1.8 released today.
