### ISSUE TITLE
Accessibility Permission Error with Finbar on MacOS 13.5

### ISSUE THREAD

**Issue by marcmagn1** [roeybiran/finbar-issues#12]
Getting the following accessibility permission error message when attempting to use Finbar on Slack: 
`Finbar is prohibited from using your Mac's accessibility features. Grant access in System Settings.`
Finbar already has the permission, it works well in other apps. Restarting does not help.
I am on MacOS 13.5 (22G74) with Finbar 13.5 (22G74)

**Comment by roeybiran** [comment]
This is extremely weird! Especially since it works well in other apps. Are you positive that Finbar works in other apps? I tried to reproduce this on my Mac but Slack works fine.

**Comment by roeybiran** [comment]
Hi, are you still experiencing this issue?

**Comment by marcmagn1** [comment]
Hello,
No, for some reason that works now.
Closing the issue.
