### ISSUE TITLE
The performance of the app could be enhanced.

### ISSUE THREAD

**Issue by cjwcommuny** [roeybiran/finbar-issues#13]
Compared to [Paletro](https://appmakes.io/paletro), Finbar's loading speed is noticeably slower. Each time I open it, I'm met with a loading animation. Improving this aspect would definitely enhance the overall user experience.

**Comment by roeybiran** [comment]
Thanks for the feedback. I’m working on improving this experience as we speak.

**Comment by roeybiran** [comment]
This enhancement has been added in the update released today. I think you’ll be satisfied. Thanks!
