### ISSUE TITLE
How to navigate back to the parent list within the app?

### ISSUE THREAD

**Issue by cjwcommuny** [roeybiran/finbar-issues#14]
<img width="919" alt="CleanShot 2023-10-12 at 12 01 58@2x" src="https://github.com/roeybiran/finbar-issues/assets/23581749/b8c817b5-b7b0-4a4c-b48e-00328d1a74ce">

As shown in the screenshot, how can I navigate back to the parent list where "Firefox" resides by keyboard?

**Comment by roeybiran** [comment]
The shortcut for this by default is <kbd>⌘</kbd><kbd>↑</kbd>, as shown in the screenshot. This could customized in System Settings.

![image](https://github.com/roeybiran/finbar-issues/assets/37002381/6b18b0ec-00f3-4175-b214-e492d935b982)

**Comment by cjwcommuny** [comment]
The shortcut appears to be asymmetric. While users utilize the "return" key to access child items, they have to employ "cmd + arrow up" to exit them. I expected a simpler method like using the "esc" or "delete" key to navigate backward.

**Comment by roeybiran** [comment]
You’re correct, and in fact an improved experience is already in the works, but since you brought this up, I’ll reopen this and leave it open.

**Comment by roeybiran** [comment]
This enhancement has been added to Finbar in the update released today. I’d love to hear your feedback on this. Thanks!
