### ISSUE TITLE
Finbar crashes

### ISSUE THREAD

**Issue by cjwcommuny** [roeybiran/finbar-issues#15]
## Environment

macOS 13.6.2
Finbar 1.12.2 (12)

## Reproduction

- Launch Finbar app
- Click "Show Finbar" in the menubar
- Finbar crashes

## Misc

- I have tried with different apps (Chrome, Finder...), it seems that the crashes doesn't relate with the background app.

## Crash report

[Finbar-2024-01-04-140056.ips.zip](https://github.com/roeybiran/finbar-issues/files/13826745/Finbar-2024-01-04-140056.ips.zip)

**Comment by roeybiran** [comment]
Thank you for the feedback and proving a crash report!
I didn’t manage to reproduce it yet, is it something that happens regularly?

**Comment by cjwcommuny** [comment]
After I reboot my Mac, Finbar stops crashing... So I will close this issue.

**Comment by roeybiran** [comment]
Thank you for updating! I will further investigate your report to try and pinpoint the issue. Do let me know if Finbar crashes again. Thanks!
