### ISSUE TITLE
Finbar crashing

### ISSUE THREAD

**Issue by mikeyp315** [roeybiran/finbar-issues#16]
Hey - just updated to Finbar 1.12.2. Running MacOS 12.6.1. Every time I try to launch, it crashes. Love Finbar so much btw!

**Comment by roeybiran** [comment]
Hi!
First of all, thank you for the kind words. It brings me utter joy that you find Finbar useful!
As for the crash, we’ll need to investigate further:
1. Does the app crash on launch, or only when the window appears?
2. How to do you launch / activate it?
3. I’ll need a crash report. Until I implement a proper crash reporter, I’d appreciate it if you could send the log file, whose path is `/Users/<YOUR USER NAME>/Library/Logs/DiagnosticReports/Finbar-<YYYY-MM-DD-HH-MM-SS>.ips`. If the app crashed multiple times, you’ll see multiple logs but the most recent (as indicated by the timestamp suffix) will suffice. Do contact me if you need further help retrieving the file.

**Comment by mikeyp315** [comment]
Only when the "search" window appears. It crashes both when I select Find from the menu bar or a keyboard shortcut. I can access the preferences and other windows (license, etc) from the menu bar.

**Comment by roeybiran** [comment]
I see. Well, it’d be of immense help if you could retrieve the aforementioned log file for me. Thanks!

**Comment by mikeyp315** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Finbar [1839]
Path:                  /Applications/Finbar.app/Contents/MacOS/Finbar
Identifier:            com.roeybiran.Finbar
Version:               1.12.2 (12)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-01-18 14:03:02.3914 -0500
OS Version:            macOS 12.6.1 (21G217)
Report Version:        12
Anonymous UUID:        70F5BDA0-0991-26C8-1CE1-05914EFF2AC5

Sleep/Wake UUID:       9672E406-FBA8-48D8-B102-0461EB300D53

Time Awake Since Boot: 1600 seconds
Time Since Wake:       408 seconds

System Integrity Protection: enabled

Crashed Thread:        7  Dispatch queue: com.apple.root.user-initiated-qos.cooperative

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000003ffff9d8b
Exception Codes:       0x0000000000000001, 0x00000003ffff9d8b
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1839]

VM Region Info: 0x3ffff9d8b is not in any region.  Bytes after previous region: 4128259468  Bytes before following region: 50465890933
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                       309e71000-309ef6000    [  532K] rw-/rwx SM=PRV  thread 6
--->  GAP OF 0xcb610a000 BYTES
      commpage (reserved)         fc0000000-1000000000   [  1.0G] ---/--- SM=NUL  ...(unallocated)

Thread 0::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff894016940 ???
1   libsystem_kernel.dylib        	    0x7ff803b3c97a mach_msg_trap + 10
2   libsystem_kernel.dylib        	    0x7ff803b3cce8 mach_msg + 56
3   CoreFoundation                	    0x7ff803c3f540 __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	    0x7ff803c3dbd0 __CFRunLoopRun + 1276
5   CoreFoundation                	    0x7ff803c3d014 CFRunLoopRunSpecific + 562
6   HIToolbox                     	    0x7ff80cd5a5e6 RunCurrentEventLoopInMode + 292
7   HIToolbox                     	    0x7ff80cd5a34a ReceiveNextEventCommon + 594
8   HIToolbox                     	    0x7ff80cd5a0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
9   AppKit                        	    0x7ff8065adfad _DPSNextEvent + 927
10  AppKit                        	    0x7ff8065ac66a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
11  AppKit                        	    0x7ff80659ed19 -[NSApplication run] + 586
12  AppKit                        	    0x7ff806572c97 NSApplicationMain + 817
13  Finbar                        	       0x102a9c9aa 0x102a99000 + 14762
14  dyld                          	       0x202ee852e start + 462

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffcbb944 0x7ff7ffcb7000 + 18756
1   runtime                       	    0x7ff7ffcc93e0 0x7ff7ffcb7000 + 74720
2   runtime                       	    0x7ff7ffccae58 0x7ff7ffcb7000 + 81496

Thread 2:: com.apple.NSEventThread
0   ???                           	    0x7ff894016940 ???
1   libsystem_kernel.dylib        	    0x7ff803b3c97a mach_msg_trap + 10
2   libsystem_kernel.dylib        	    0x7ff803b3cce8 mach_msg + 56
3   CoreFoundation                	    0x7ff803c3f540 __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	    0x7ff803c3dbd0 __CFRunLoopRun + 1276
5   CoreFoundation                	    0x7ff803c3d014 CFRunLoopRunSpecific + 562
6   AppKit                        	    0x7ff80671b9ce _NSEventThread + 132
7   libsystem_pthread.dylib       	    0x7ff803b794e1 _pthread_start + 125
8   libsystem_pthread.dylib       	    0x7ff803b74f6b thread_start + 15

Thread 3:
0   runtime                       	    0x7ff7ffcd9814 0x7ff7ffcb7000 + 141332

Thread 4:
0   runtime                       	    0x7ff7ffcd9814 0x7ff7ffcb7000 + 141332

Thread 5:
0   runtime                       	    0x7ff7ffcd9814 0x7ff7ffcb7000 + 141332

Thread 6:
0   runtime                       	    0x7ff7ffcd9814 0x7ff7ffcb7000 + 141332

Thread 7 Crashed::  Dispatch queue: com.apple.root.user-initiated-qos.cooperative
0   <translation info unavailable>	       0x1034ec824 ???
1   <translation info unavailable>	       0x103458a9c ???
2   Finbar                        	       0x102b42e94 0x102a99000 + 695956
3   Finbar                        	       0x102b42f7e 0x102a99000 + 696190
4   Finbar                        	       0x102b41832 0x102a99000 + 690226
5   Finbar                        	       0x102b41eed 0x102a99000 + 691949
6   Finbar                        	       0x102b44326 0x102a99000 + 701222
7   Finbar                        	       0x102cf9fda 0x102a99000 + 2494426
8   Finbar                        	       0x102cfc32e 0x102a99000 + 2503470
9   Finbar                        	       0x102cfede0 0x102a99000 + 2514400
10  Finbar                        	       0x102cfe745 0x102a99000 + 2512709
11  Finbar                        	       0x102cfb257 0x102a99000 + 2499159
12  Finbar                        	       0x102cfc32e 0x102a99000 + 2503470
13  Finbar                        	       0x102cfede0 0x102a99000 + 2514400
14  Finbar                        	       0x102cfe745 0x102a99000 + 2512709
15  Finbar                        	       0x102cfb257 0x102a99000 + 2499159
16  Finbar                        	       0x102cf9b33 0x102a99000 + 2493235
17  Finbar                        	       0x102cfd0e9 0x102a99000 + 2506985
18  Finbar                        	       0x102af8e83 0x102a99000 + 392835
19  Finbar                        	       0x102b0b8e1 0x102a99000 + 469217

Thread 8:
0   runtime                       	    0x7ff7ffcd9814 0x7ff7ffcb7000 + 141332


Thread 7 crashed with X86 Thread State (64-bit):
  rax: 0x00000003ffff9d8b  rbx: 0x0000000000000000  rcx: 0x0000000309b3e601  rdx: 0x0000000000000000
  rdi: 0x0000000309b3e618  rsi: 0x00006000010f477c  rbp: 0x0000000309b3e650  rsp: 0x0000000309b3e5a0
   r8: 0x00000000000000ff   r9: 0x0000000000000002  r10: 0x00007fa3d61ab660  r11: 0x00007ff803c13568
  r12: 0x0000000309b3e688  r13: 0x00006000010f4320  r14: 0x00006000010f4760  r15: 0x00006000010f4760
  rip: <unavailable>       rfl: 0x0000000000000203
 tmp0: 0x0000000102b41196 tmp1: 0x0000000102b41196 tmp2: 0x00000001034ec818


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff803b3b000 -     0x7ff803b72fff libsystem_kernel.dylib (*) <0ea0d8ac-c27b-3a71-a59b-ec3a6f116acf> /usr/lib/system/libsystem_kernel.dylib
    0x7ff803bc0000 -     0x7ff8040c0fff com.apple.CoreFoundation (6.9) <bddb824d-15df-3210-88e8-6aac5c154403> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7ff80cd2c000 -     0x7ff80d01ffff com.apple.HIToolbox (2.1.1) <06fdecd6-9f69-397b-b1e2-a8226c0ba7ed> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7ff80656f000 -     0x7ff8073fefff com.apple.AppKit (6.9) <d2726161-3c3f-3b59-bd8d-4a088d4545ef> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x102a99000 -        0x102d9cfff com.roeybiran.Finbar (1.12.2) <8c914d2b-39d8-304c-bd6c-d61bbb62b34e> /Applications/Finbar.app/Contents/MacOS/Finbar
       0x202ee3000 -        0x202f4efff dyld (*) <7b87a986-a153-33c4-8470-d56410b7f9d5> /usr/lib/dyld
    0x7ff7ffcb7000 -     0x7ff7ffce6fff runtime (*) <419e294c-6e25-389b-a0f2-b3d7c56a046e> /usr/libexec/rosetta/runtime
    0x7ff803b73000 -     0x7ff803b7efff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=2.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.0G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               512K        4 
Activity Tracing                   256K        1 
CG image                          1296K       56 
ColorSync                          236K       28 
CoreAnimation                     4872K      150 
CoreGraphics                        16K        3 
CoreUI image data                 5108K       35 
Foundation                          48K        2 
Kernel Alloc Once                    8K        1 
MALLOC                           328.4M       68 
MALLOC guard page                  288K       13 
MALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     4096K        2 
Rosetta Generic                   1036K      256 
Rosetta IndirectBranch            2048K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack               160K       16 
Rosetta Thread Context             160K       16 
SQLite page cache                   64K        1 
STACK GUARD                         20K        5 
Stack                             11.6M        8 
Stack Guard                       56.0M        3 
VM_ALLOCATE                       5112K       23 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__CTF                               756        1 
__DATA                            30.7M      523 
__DATA_CONST                      30.3M      343 
__DATA_DIRTY                      1673K      209 
__FONT_DATA                          4K        1 
__LINKEDIT                       705.3M       18 
__OBJC_RO                         82.8M        1 
__OBJC_RW                         3200K        2 
__TEXT                           517.8M      539 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
libnetwork                         640K       16 
mapped file                        5.0G      746 
shared memory                      800K       12 
unshared pmap                      9.8M        8 
===========                     =======  ======= 
TOTAL                              8.4G     3126 
TOTAL, minus reserved VM space     6.9G     3126 



-----------
Full Report
-----------

{"app_name":"Finbar","timestamp":"2024-01-18 14:03:02.00 -0500","app_version":"1.12.2","slice_uuid":"8c914d2b-39d8-304c-bd6c-d61bbb62b34e","build_version":"12","platform":1,"bundleID":"com.roeybiran.Finbar","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.1 (21G217)","incident_id":"CCCF863F-C45A-43C1-B394-6C9D72C034E5","name":"Finbar"}
{
  "uptime" : 1600,
  "procLaunch" : "2024-01-18 14:01:12.1289 -0500",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 36677623562,
  "coalitionID" : 671,
  "osVersion" : {
    "train" : "macOS 12.6.1",
    "build" : "21G217",
    "releaseType" : "User"
  },
  "captureTime" : "2024-01-18 14:03:02.3914 -0500",
  "incident" : "CCCF863F-C45A-43C1-B394-6C9D72C034E5",
  "bug_type" : "309",
  "pid" : 1839,
  "procExitAbsTime" : 39323831987,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "Finbar",
  "procPath" : "\/Applications\/Finbar.app\/Contents\/MacOS\/Finbar",
  "bundleInfo" : {"CFBundleShortVersionString":"1.12.2","CFBundleVersion":"12","CFBundleIdentifier":"com.roeybiran.Finbar"},
  "storeInfo" : {"deviceIdentifierForVendor":"2F88B3FC-A96B-50B8-8533-8B1B7F3F93D9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.roeybiran.Finbar",
  "crashReporterKey" : "70F5BDA0-0991-26C8-1CE1-05914EFF2AC5",
  "wakeTime" : 408,
  "sleepWakeUUID" : "9672E406-FBA8-48D8-B102-0461EB300D53",
  "sip" : "enabled",
  "vmRegionInfo" : "0x3ffff9d8b is not in any region.  Bytes after previous region: 4128259468  Bytes before following region: 50465890933\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      Stack                       309e71000-309ef6000    [  532K] rw-\/rwx SM=PRV  thread 6\n--->  GAP OF 0xcb610a000 BYTES\n      commpage (reserved)         fc0000000-1000000000   [  1.0G] ---\/--- SM=NUL  ...(unallocated)",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000003ffff9d8b","rawCodes":[1,17179843979],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000003ffff9d8b"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":1839},
  "vmregioninfo" : "0x3ffff9d8b is not in any region.  Bytes after previous region: 4128259468  Bytes before following region: 50465890933\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      Stack                       309e71000-309ef6000    [  532K] rw-\/rwx SM=PRV  thread 6\n--->  GAP OF 0xcb610a000 BYTES\n      commpage (reserved)         fc0000000-1000000000   [  1.0G] ---\/--- SM=NUL  ...(unallocated)",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 7,
  "threads" : [{"id":20026,"queue":"com.apple.main-thread","frames":[{"imageOffset":140705611737408,"imageIndex":0},{"imageOffset":6522,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":7400,"symbol":"mach_msg","symbolLocation":56,"imageIndex":1},{"imageOffset":521536,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":2},{"imageOffset":515024,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":2},{"imageOffset":512020,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":2},{"imageOffset":189926,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":189258,"symbol":"ReceiveNextEventCommon","symbolLocation":594,"imageIndex":3},{"imageOffset":188645,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":70,"imageIndex":3},{"imageOffset":257965,"symbol":"_DPSNextEvent","symbolLocation":927,"imageIndex":4},{"imageOffset":251498,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1394,"imageIndex":4},{"imageOffset":195865,"symbol":"-[NSApplication run]","symbolLocation":586,"imageIndex":4},{"imageOffset":15511,"symbol":"NSApplicationMain","symbolLocation":817,"imageIndex":4},{"imageOffset":14762,"imageIndex":5},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":6}]},{"id":20031,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18756,"imageIndex":7},{"imageOffset":74720,"imageIndex":7},{"imageOffset":81496,"imageIndex":7}]},{"id":20045,"name":"com.apple.NSEventThread","frames":[{"imageOffset":140705611737408,"imageIndex":0},{"imageOffset":6522,"symbol":"mach_msg_trap","symbolLocation":10,"imageIndex":1},{"imageOffset":7400,"symbol":"mach_msg","symbolLocation":56,"imageIndex":1},{"imageOffset":521536,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":319,"imageIndex":2},{"imageOffset":515024,"symbol":"__CFRunLoopRun","symbolLocation":1276,"imageIndex":2},{"imageOffset":512020,"symbol":"CFRunLoopRunSpecific","symbolLocation":562,"imageIndex":2},{"imageOffset":1755598,"symbol":"_NSEventThread","symbolLocation":132,"imageIndex":4},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":8},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":8}]},{"id":21686,"frames":[{"imageOffset":141332,"imageIndex":7}]},{"id":21831,"frames":[{"imageOffset":141332,"imageIndex":7}]},{"id":22040,"frames":[{"imageOffset":141332,"imageIndex":7}]},{"id":22041,"frames":[{"imageOffset":141332,"imageIndex":7}]},{"triggered":true,"id":22174,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":13047686736},"r12":{"value":13047686792},"rosetta":{"tmp2":{"value":4350461976},"tmp1":{"value":4340322710},"tmp0":{"value":4340322710}},"rbx":{"value":0},"r8":{"value":255},"r15":{"value":105553134045024},"r10":{"value":140341648471648},"rdx":{"value":0},"rdi":{"value":13047686680},"r9":{"value":2},"r13":{"value":105553134043936},"rflags":{"value":515},"rax":{"value":17179843979},"rsp":{"value":13047686560},"r11":{"value":140703191610728,"symbolLocation":0,"symbol":"-[__NSCFType release]"},"rcx":{"value":13047686657},"r14":{"value":105553134045024},"rsi":{"value":105553134045052}},"queue":"com.apple.root.user-initiated-qos.cooperative","frames":[{"imageOffset":4350461988,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":4349856412,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":695956,"imageIndex":5},{"imageOffset":696190,"imageIndex":5},{"imageOffset":690226,"imageIndex":5},{"imageOffset":691949,"imageIndex":5},{"imageOffset":701222,"imageIndex":5},{"imageOffset":2494426,"imageIndex":5},{"imageOffset":2503470,"imageIndex":5},{"imageOffset":2514400,"imageIndex":5},{"imageOffset":2512709,"imageIndex":5},{"imageOffset":2499159,"imageIndex":5},{"imageOffset":2503470,"imageIndex":5},{"imageOffset":2514400,"imageIndex":5},{"imageOffset":2512709,"imageIndex":5},{"imageOffset":2499159,"imageIndex":5},{"imageOffset":2493235,"imageIndex":5},{"imageOffset":2506985,"imageIndex":5},{"imageOffset":392835,"imageIndex":5},{"imageOffset":469217,"imageIndex":5}]},{"id":22175,"frames":[{"imageOffset":141332,"imageIndex":7}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703190724608,
    "size" : 229376,
    "uuid" : "0ea0d8ac-c27b-3a71-a59b-ec3a6f116acf",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703191269376,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5246976,
    "uuid" : "bddb824d-15df-3210-88e8-6aac5c154403",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1866"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703343755264,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3096576,
    "uuid" : "06fdecd6-9f69-397b-b1e2-a8226c0ba7ed",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703234977792,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15269888,
    "uuid" : "d2726161-3c3f-3b59-bd8d-4a088d4545ef",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.60.148"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4339634176,
    "CFBundleShortVersionString" : "1.12.2",
    "CFBundleIdentifier" : "com.roeybiran.Finbar",
    "size" : 3162112,
    "uuid" : "8c914d2b-39d8-304c-bd6c-d61bbb62b34e",
    "path" : "\/Applications\/Finbar.app\/Contents\/MacOS\/Finbar",
    "name" : "Finbar",
    "CFBundleVersion" : "12"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8639098880,
    "size" : 442368,
    "uuid" : "7b87a986-a153-33c4-8470-d56410b7f9d5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703125172224,
    "size" : 196608,
    "uuid" : "419e294c-6e25-389b-a0f2-b3d7c56a046e",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703190953984,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703187697664,
  "size" : 19331678208,
  "uuid" : "47e1dd7d-5e37-3ec3-a85c-901263ec66b5"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=2.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.0G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               512K        4 \nActivity Tracing                   256K        1 \nCG image                          1296K       56 \nColorSync                          236K       28 \nCoreAnimation                     4872K      150 \nCoreGraphics                        16K        3 \nCoreUI image data                 5108K       35 \nFoundation                          48K        2 \nKernel Alloc Once                    8K        1 \nMALLOC                           328.4M       68 \nMALLOC guard page                  288K       13 \nMALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nRosetta Arena                     4096K        2 \nRosetta Generic                   1036K      256 \nRosetta IndirectBranch            2048K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack               160K       16 \nRosetta Thread Context             160K       16 \nSQLite page cache                   64K        1 \nSTACK GUARD                         20K        5 \nStack                             11.6M        8 \nStack Guard                       56.0M        3 \nVM_ALLOCATE                       5112K       23 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__CTF                               756        1 \n__DATA                            30.7M      523 \n__DATA_CONST                      30.3M      343 \n__DATA_DIRTY                      1673K      209 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       705.3M       18 \n__OBJC_RO                         82.8M        1 \n__OBJC_RW                         3200K        2 \n__TEXT                           517.8M      539 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nlibnetwork                         640K       16 \nmapped file                        5.0G      746 \nshared memory                      800K       12 \nunshared pmap                      9.8M        8 \n===========                     =======  ======= \nTOTAL                              8.4G     3126 \nTOTAL, minus reserved VM space     6.9G     3126 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.root.user-initiated-qos.cooperative"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "61af99aeda72d16a4beb7756",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "629fe54ebc762c0b6f758b6b"
      },
      "deploymentId" : 240000409
    },
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "631730a28520965d1cba0681"
      },
      "deploymentId" : 240000143
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by mikeyp315** [comment]
> I see. Well, it’d be of immense help if you could retrieve the aforementioned log file for me. Thanks!
> 
> Also: another user has reported a similar issue recently, which was solved by a restart of the Mac. Did you try that?

I did restart, but that didn't fix it.

**Comment by roeybiran** [comment]
Possibly related to #15.

**Comment by roeybiran** [comment]
Hi @mikeyp315, I’d like to share with you a private beta version of FInbar which hopefully fixes the crashes. What’s the best way to contact you for this purpose?

**Comment by roeybiran** [comment]
Fixed in v1.12.3. Thanks for providing the crash log!
