### ISSUE TITLE
Crashes when adding shortcut

### ISSUE THREAD

**Issue by JDENredden** [roeybiran/finbar-issues#17]
Finbar crashes as soon as I press any key when trying to add a keyboard shortcut to activate.

I've attached crash reports. I've rebooted computer and same issue. Currently stuck with no keyboard shortcut to activate Finbar which reduces it usefulness quite a lot.

[Archive.zip](https://github.com/roeybiran/finbar-issues/files/14861721/Archive.zip)

**Comment by roeybiran** [comment]
Thank you so much for reporting — I was able to reproduce the issue. Expect a fix later today!

**Comment by JDENredden** [comment]
Nice thank you!

**Comment by roeybiran** [comment]
Fixed in v1.13.1 released today!
Sorry for the delay and for your initial negative experience with my app. I’m certain it’d change for the better 🙏
