### ISSUE TITLE
Possible to not search in Apple/recent items

### ISSUE THREAD

**Issue by TausendMedien** [roeybiran/finbar-issues#20]
There are a lot of objects in Apple/recents items which clutter the otherwise clean results of finbar. I don't search for these object when using finbar. How can I hide them? 

Maybe the rule editor would be my solution. But I don't find a way how to access the rule editor.

**Comment by roeybiran** [comment]
Hi and thanks for using the issue tracker!

The rule editor is accessible by in the settings:

![CleanShot 2024-10-16 at 11 21 46@2x](https://github.com/user-attachments/assets/ad64b5b7-58a8-4b67-b6dd-6f4332da52ac)

To exclude the Apple menu, define the following (taken from my own configuration):

![CleanShot 2024-10-16 at 11 22 44@2x](https://github.com/user-attachments/assets/5d6d26f8-d5f8-4ccb-98a9-a251ad73bde0)

Message me if you need further help. Thank you!

**Comment by TausendMedien** [comment]
Thank you for your help!

Would be great to have these included in the software as an option already
pre-installed.
For example during the installation process You asked:
“Where the rule editor, you can customise Finn Bar.
Hear an example which excludes the Apple menu with The Recently started
Programs as well as several browser history entries. Do you want to
activate them?”

Best,
Uli

Roey Biran ***@***.***> schrieb am Mi. 16. Okt. 2024 um 10:25:

**Comment by roeybiran** [comment]
Thanks for the feedback! I’ll definitely consider that.
