### ISSUE TITLE
Bug: Automatically center window

### ISSUE THREAD

**Issue by rmansour** [roeybiran/finbar-issues#4]
When working with multiple displays, the window isn't centred across displays. Let's say it is first launched on the MacBook screen and when launched on the other screen thereafter, it's launched not centred. 
 
Although the option exists in the options menu, it'd be nice to have it do that automatically.

**Comment by roeybiran** [comment]
This is a known bug. I’m working on it as we speak!

**Comment by roeybiran** [comment]
Fixed in v1.5.1. You’ll probably have to center the window through the menu one more time.

And of course, do tell me if the issue persists please. 

Thank you for your continued interest in my app 🙏

**Comment by rmansour** [comment]
Awesome work! Seems ok for now, will keep monitoring.

Thx for an awesome app!
