### ISSUE TITLE
Finbar not displaying child items on mac os Sonoma Beta

### ISSUE THREAD

**Issue by ramirocantu** [roeybiran/finbar-issues#6]
So i just started trying out finbar, and while trying to use i don't get any menu items to populate, it could be multiple things but most likely its that mac os sonoma is not yet compatible? I haven't purchased the app yet so maybe that could be the cause?

<img width="1680" alt="image" src="https://github.com/roeybiran/finbar-issues/assets/19764244/8b1b2a3e-83ec-4d8b-9b7c-ef6460da1822">
 
<img width="787" alt="image" src="https://github.com/roeybiran/finbar-issues/assets/19764244/ada1cb58-c5f3-4c1c-96b8-dc3c4f30b1cf">
<img width="787" alt="image" src="https://github.com/roeybiran/finbar-issues/assets/19764244/5c3d34c3-2403-4163-8755-f8d47e8d8d8b">

**Comment by roeybiran** [comment]
First of all,

Thank you for using this channel for feedback, so others could benefit as well. 

Apple introduced a bug in Sonoma that severely impacts Finbar. I can easily work around it, but since Sonoma is still in closed beta, I rather wait some more with the hopes that Apple fixes this on their end. It has nothing to do with you not buying a license.

I already filed feedback.

**Comment by kstrauser** [comment]
Asking purely out of curiosity: what's the bug? I found this report after the Sonoma Public Beta killed my Finbar, too. I installed this _knowing_ the beta was bound to break things, and it's done a number on all sorts of apps I use daily.

**Comment by roeybiran** [comment]
Sorry, I missed your message! The bug stems from a change in the type of some accessibility attributes Finbar relies on.

On a general note: rest assured Finbar **will** work **perfectly** in Sonoma — you have nothing to worry about. I’m just waiting for the GM before I apply the workaround to the production version of the app, with the hopes that Apple fixes the bug by then.

**Comment by roeybiran** [comment]
Fixed in v1.10.
