### ISSUE TITLE
Right arrow key should activate items with disclosure chevrons

### ISSUE THREAD

**Issue by fantismo** [roeybiran/finbar-issues#7]
When navigating MacOS menus using a keyboard, the right arrow key discloses submenus (similarly, the left arrow key navigates back up the chain). Finbar, as a replacement / accelerator for accessing menu items, should mimic this behavior.

This is not the case using Finbar 1.7.3, which places focus for left / right arrow keys in the text input (Search) field. At the same time, the up / down arrow keys have the expected behavior of acting upon the search results. All arrow keys should affect the same portion of the UI.

The ability to fully navigate menu items (search results) from the arrow keys is more valuable than the ability to move the textual input cursor. This is further exasperated by the small number of keys Finbar appears to require to access long menu titles (the New Tab example video on the product page highlights this precisely [0]). 

This was the first thing I tried to do with the app. Having to move to the Return key to activate a submenu and then back to the arrow keys to navigate is a non-starter. This would be especially problematic on Apple laptops that lack the inverted T keys (the so-called "butterfly keyboards"). In keeping with the behavior of the native menus, Finbar should be fully navigable via the arrow keys. The current behavior does not feel Mac-like.

In case this sounds like criticism, it's not. The app is very intriguing and clearly polished. Cheers!

[0] https://res.cloudinary.com/roeybiran/video/upload/f_auto:video,q_auto/fast_fgeio4

**Comment by fantismo** [comment]
If the goal is to behave similarly to app launchers and Spotlight, then I agree with your logic. My feedback was from the point of view that Finbar is an extension of the menu bar. Best,DanSent from my mobile device.On Jul 26, 2023, at 12:38 PM, Roey Biran ***@***.***> wrote:﻿
First of all, thank you for this invaluable, eloquent feedback. This is the only way to make Finbar better.
What you’re bringing up here is an interesting UX question. When I built Finbar I had assumed that tampering with the caret’s inline movement would be much more detrimental to the user experience than having press the tab key once (I made sure the list is always one tab away from the search field!) and get full control over the outline.

The current behavior does not feel Mac-like.

I’m not sure I agree with this statement. Almost all of the “Spotlight”-style apps I’ve tried (including Spotlight itself), from which Finbar naturally draws its conventions, behave this way — inline movement is not interfered with, block movement in intercepted to control the list, and newline insertion is replaced with executing the selection. The only app I know that’s handles this in a unique, excellent way is LaunchBar, where text input is actually ephemeral (this has price though, I found LaunchBar to have a high learning curve).
Also, many of those apps impose a permanent focused-like (or “highlighted”) appearance to their list of items, even if it’s the search field that’s always focused. I find this confusing. In Finbar I deliberately chose not to do so in order to signal that there are behavioral changes when shifting focus between searching and browsing.
While I consider whether this should be the default, let me propose a different solution: Finbar exposes its functionality through an option menu, including menu item to expand and collapse outline item. Using the standard macOS mechanism of creating app shortcuts, you could bind the arrow keys to those items. I tried this myself and it works beautifully. It even falls back to standard caret movement when the current item can’t be expanded or collapsed!

**Comment by roeybiran** [comment]
The goal is less about behaving like a specific style of app, but rather doing what users would expect the most. Nonetheless I’m still contemplating your feedback and thinking about the best way to go about this. Regardless, have you tried assigning custom shortcuts as I’ve suggested?

Roey

**Comment by fantismo** [comment]
I’m familiar with the feature. I’ve had custom shortcuts augmenting my outgoing mail accounts for a number of years.I still think users are more likely to be surprised by the behavior if thinking of the app as an extension of the OS’s menus, but I may be wrong on that. I concede that I’m ultra-nerdy and may be out of step with typical users. However, I don’t think users who are attracted to such an app are typical: they’re probably pretty nerdy. Best,DanSent from my mobile device.On Jul 28, 2023, at 2:27 AM, Roey Biran ***@***.***> wrote:﻿
The goal is less about behaving like a specific style of app, but rather doing what users would expect the most. Nonetheless I’m still contemplating your feedback and thinking about the best way to go about this. Regardless, have you tried assigning custom shortcuts as I’ve suggested?
Roey

**Comment by roeybiran** [comment]
Thanks for the input. I must admit that I’ve been trying your suggestions myself over the last couple of days and they’ve grown on me. I may very well make them the default, but I need to think about this some more. I’m leaving this ticket open in the meantime.

**Comment by roeybiran** [comment]
I’ve decided to apply your suggestion, and starting in the next version of Finbar, the default key equivalents for expanding and collapsing menu items will be the arrow keys. Thanks for your feedback! 🙏
