### ISSUE TITLE
Disable in certain Apps

### ISSUE THREAD

**Issue by onedrop2000** [roeybiran/finbar-issues#8]
Hi there,
Is it possible to disable the shortcut to Applications which already have a command pallete (e.g. Obsidian). So it would "allways" stay the same shortcut: e.g Command+P, and either the command pallet shows up, or the menu-bar-search.

Thanks + kind Regards,
Johannes

**Comment by roeybiran** [comment]
This is definitely doable and in fact other have asked for this. I’ll add this in the next couple of updates. Stay tuned!

**Comment by roeybiran** [comment]
Finbar v1.10 released today adds this feature.
