### ISSUE TITLE
Not obvious how to nest rules

### ISSUE THREAD

**Issue by kstrauser** [roeybiran/finbar-issues#9]
It took me the longest time to figure out how to add "any/all" rules. I don't know how I hadn't already stumbled across option-clicking the plus sign before, but I hadn't. I didn't even realize it was possible at first and was going to ask for it as a feature request. (Note: this is all on me, not you! Your docs were clear and accurate; I just didn't know how to use the rule editor.)

A sentence like "option-click to add nested rules", or maybe even a screenshot demonstrating it, would be helpful to other clueless people like me. 🙂

**Comment by roeybiran** [comment]
Well, I wouldn’t say this is on you either — I’d blame Apple and their constant neglect of macOS for this. The UI component we’re discussing hasn’t received significant updates in ages I believe, including those that’d increase its affordance (it’s pretty absurd that a core functionality of the component is hidden behind a press on the option key). I’ll confess too that when I first used it in the Finder it took me way too long to understand this. But once you do, it’s an amazing piece of UI.

**Comment by roeybiran** [comment]
The user guide now links to an official Apple support article that deals with this. It’s a great intro to rule editors.
